#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Template-Toolkit
Version  : 3.009
Release  : 14
URL      : https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/Template-Toolkit-3.009.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/Template-Toolkit-3.009.tar.gz
Summary  : 'comprehensive template processing system'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Template-Toolkit-bin = %{version}-%{release}
Requires: perl-Template-Toolkit-man = %{version}-%{release}
Requires: perl-Template-Toolkit-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(AppConfig)
BuildRequires : perl(CGI)
BuildRequires : perl(HTML::Entities)
BuildRequires : perl(Test::LeakTrace)

%description
#========================================================================
# Template Toolkit - parser
#========================================================================

%package bin
Summary: bin components for the perl-Template-Toolkit package.
Group: Binaries

%description bin
bin components for the perl-Template-Toolkit package.


%package dev
Summary: dev components for the perl-Template-Toolkit package.
Group: Development
Requires: perl-Template-Toolkit-bin = %{version}-%{release}
Provides: perl-Template-Toolkit-devel = %{version}-%{release}
Requires: perl-Template-Toolkit = %{version}-%{release}

%description dev
dev components for the perl-Template-Toolkit package.


%package man
Summary: man components for the perl-Template-Toolkit package.
Group: Default

%description man
man components for the perl-Template-Toolkit package.


%package perl
Summary: perl components for the perl-Template-Toolkit package.
Group: Default
Requires: perl-Template-Toolkit = %{version}-%{release}

%description perl
perl components for the perl-Template-Toolkit package.


%prep
%setup -q -n Template-Toolkit-3.009
cd %{_builddir}/Template-Toolkit-3.009

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tpage
/usr/bin/ttree

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Template.3
/usr/share/man/man3/Template::Base.3
/usr/share/man/man3/Template::Config.3
/usr/share/man/man3/Template::Constants.3
/usr/share/man/man3/Template::Context.3
/usr/share/man/man3/Template::Directive.3
/usr/share/man/man3/Template::Document.3
/usr/share/man/man3/Template::Exception.3
/usr/share/man/man3/Template::FAQ.3
/usr/share/man/man3/Template::Filters.3
/usr/share/man/man3/Template::Grammar.3
/usr/share/man/man3/Template::Iterator.3
/usr/share/man/man3/Template::Manual.3
/usr/share/man/man3/Template::Manual::Config.3
/usr/share/man/man3/Template::Manual::Credits.3
/usr/share/man/man3/Template::Manual::Directives.3
/usr/share/man/man3/Template::Manual::Filters.3
/usr/share/man/man3/Template::Manual::Internals.3
/usr/share/man/man3/Template::Manual::Intro.3
/usr/share/man/man3/Template::Manual::Plugins.3
/usr/share/man/man3/Template::Manual::Syntax.3
/usr/share/man/man3/Template::Manual::VMethods.3
/usr/share/man/man3/Template::Manual::Variables.3
/usr/share/man/man3/Template::Manual::Views.3
/usr/share/man/man3/Template::Modules.3
/usr/share/man/man3/Template::Namespace::Constants.3
/usr/share/man/man3/Template::Parser.3
/usr/share/man/man3/Template::Plugin.3
/usr/share/man/man3/Template::Plugin::Assert.3
/usr/share/man/man3/Template::Plugin::CGI.3
/usr/share/man/man3/Template::Plugin::Datafile.3
/usr/share/man/man3/Template::Plugin::Date.3
/usr/share/man/man3/Template::Plugin::Directory.3
/usr/share/man/man3/Template::Plugin::Dumper.3
/usr/share/man/man3/Template::Plugin::File.3
/usr/share/man/man3/Template::Plugin::Filter.3
/usr/share/man/man3/Template::Plugin::Format.3
/usr/share/man/man3/Template::Plugin::HTML.3
/usr/share/man/man3/Template::Plugin::Image.3
/usr/share/man/man3/Template::Plugin::Iterator.3
/usr/share/man/man3/Template::Plugin::Math.3
/usr/share/man/man3/Template::Plugin::Pod.3
/usr/share/man/man3/Template::Plugin::Procedural.3
/usr/share/man/man3/Template::Plugin::Scalar.3
/usr/share/man/man3/Template::Plugin::String.3
/usr/share/man/man3/Template::Plugin::Table.3
/usr/share/man/man3/Template::Plugin::URL.3
/usr/share/man/man3/Template::Plugin::View.3
/usr/share/man/man3/Template::Plugin::Wrap.3
/usr/share/man/man3/Template::Plugins.3
/usr/share/man/man3/Template::Provider.3
/usr/share/man/man3/Template::Service.3
/usr/share/man/man3/Template::Stash.3
/usr/share/man/man3/Template::Stash::Context.3
/usr/share/man/man3/Template::Stash::XS.3
/usr/share/man/man3/Template::Test.3
/usr/share/man/man3/Template::Toolkit.3
/usr/share/man/man3/Template::Tools.3
/usr/share/man/man3/Template::Tools::tpage.3
/usr/share/man/man3/Template::Tools::ttree.3
/usr/share/man/man3/Template::Tutorial.3
/usr/share/man/man3/Template::Tutorial::Datafile.3
/usr/share/man/man3/Template::Tutorial::Web.3
/usr/share/man/man3/Template::VMethods.3
/usr/share/man/man3/Template::View.3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/tpage.1
/usr/share/man/man1/ttree.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Base.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Config.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Constants.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Context.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Directive.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Document.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Exception.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/FAQ.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Filters.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Grammar.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Iterator.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Config.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Credits.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Directives.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Filters.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Internals.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Intro.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Plugins.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Syntax.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/VMethods.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Variables.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Manual/Views.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Modules.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Namespace/Constants.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Parser.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Assert.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/CGI.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Datafile.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Date.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Directory.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Dumper.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/File.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Filter.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Format.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/HTML.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Image.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Iterator.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Math.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Pod.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Procedural.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Scalar.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/String.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Table.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/URL.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/View.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugin/Wrap.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Plugins.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Provider.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Service.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Stash.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Stash/Context.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Stash/XS.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Test.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Toolkit.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Tools.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Tools/tpage.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Tools/ttree.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Tutorial.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Tutorial/Datafile.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/Tutorial/Web.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/VMethods.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Template/View.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Template/Stash/XS/XS.so
